### ISSUE TITLE
Uncaught TypeError: _statusBarItem2.default is not a function

### ISSUE THREAD

**Issue by raslake** [atom/line-ending-selector#24] opened 2016-02-25 04:35 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Mac OS X 10.10.5
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /Users/xiaoguo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/line-ending-selector/lib/main.js:85

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/Users/xiaoguo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/line-ending-selector/lib/main.js:85:23)
    at Provider.module.exports.Provider.provide (/Users/xiaoguo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Users/xiaoguo/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Kampfmoehre** [comment] 2016-03-03 08:00
Also have this problem right after I start atom.

This also seems do disable some of my other packages which makes atom completely useless for me. I tried to build atom from master brnach as well as last release.
Disabling the package hides the error message, but some of my other packages (including project manager and phpunit) still won't work.

**Atom Version**: 1.7.0-dev-2bdf4be
**System**: Linux Mint
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.1

### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /usr/local/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/usr/local/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73:23)
    at Provider.module.exports.Provider.provide (/usr/local/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/local/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```

### Commands

```
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autosave",
      "welcome",
      "package-generator",
      "open-on-github",
      "bookmarks",
      "keyboard-localization"
    ],
    "ignoredNames": [
      ".git",
      ".coverage",
      "tags",
      "composer.*",
      ".tags_swap",
      "tmp"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify",
      "tool-bar",
      "linter",
      "atom-dark-ui",
      "highlight-line",
      "last-cursor-position",
      "phpunit"
    ],
    "projectHome": "/home/user/dev",
    "themes": [
      "atom-dark-ui",
      "afterglow-like"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
afterglow-like, v0.2.1
color-picker, v2.1.1
docblockr, v0.7.3
file-icons, v1.6.17
flex-tool-bar, v0.7.3
highlight-line, v0.11.1
last-cursor-position, v0.9.0
linter, v1.11.3
linter-php, v1.2.0
php-cs-fixer, v2.5.6
phpunit, v1.2.0
pigments, v0.24.2
project-manager, v2.7.6
sync-settings, v0.6.0
tool-bar, v0.2.1
tree-view-git-status, v0.2.3

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2016-03-03 08:03
Can you reproduce the problem in Safe Mode?

To launch Safe Mode:
1. Completely exit all instances of Atom
2. Launch Atom with the command `atom --safe`

**Comment by Kampfmoehre** [comment] 2016-03-03 08:57
After running script/clean and rebuild the latest version via git checkout $(git describe --tags `git rev-list --tags --max-count=1`) the problem no longer occurs.
I rebuild atom from master (after running script/clean again) and it still works.

**Comment by Kampfmoehre** [comment] 2016-04-11 06:37
After building from latest master I've got the problem again. I tried launching atom in safe mode, but the problem persists.
After checking out latest release (1.7.0 dev 579b6b7) it works again.

**Comment by damieng** [comment] 2016-09-30 03:15
Dupe of https://github.com/atom/line-ending-selector/issues/19

**Closed as completed by damieng** 2016-09-30 03:15 UTC
Labels: uncaught-exception
