### ISSUE TITLE
Uncaught TypeError: _statusBarItem2.default is not a constructor

### ISSUE THREAD

**Issue by aranguri** [atom/line-ending-selector#32] opened 2016-08-13 13:18 UTC
Whenever I open Atom in Ubuntu 16.04, I receive this error:
"Uncaught TypeError: _statusBarItem2.default is not a constructor"
usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73
How can I solve?

**Comment by nahidex** [comment] 2016-08-21 05:39
I have exactly same issue with Ubuntu 16.04.

**Comment by sean666888** [comment] 2016-08-21 21:48
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.9.9
**System**: Ubuntu 16.04.1
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.5.0

### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a constructor

```
At /usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73

TypeError: _statusBarItem2.default is not a constructor
    at Object.consumeStatusBar (/usr/share/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73:23)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Config

``` json
{}
```

### Installed Packages

``` coffee
# User
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (active)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.0 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.0 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.1 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.1 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (inactive)
timecop, v0.33.1 (inactive)
tree-view, v0.208.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (inactive)
language-gfm, v0.86.0 (inactive)
language-git, v0.13.0 (inactive)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.0 (inactive)
language-less, v0.29.3 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.21.1 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by edencorbin** [comment] 2016-09-26 00:13
Same issue here, using Deepin 15.3, Ubuntu 16 based I do believe.

**Comment by seajean** [comment] 2017-02-15 09:05
-

**Comment by wayrex** [comment] 2017-05-17 14:48
++

**Comment by niclonious** [comment] 2017-06-14 06:23
The same, Ubuntu 16.04.4

**Comment by necorobsd** [comment] 2017-06-19 07:19
++

**Comment by jrich8573** [comment] 2017-06-19 14:17
Same error on Windows 7, RHEL 7, and macos.

**Comment by Saliva520319** [comment] 2017-06-25 14:23
++

**Comment by Jarvvski** [comment] 2017-06-25 14:50
++

**Comment by ncarreiro** [comment] 2017-06-26 20:55
Same problem in Ubuntu 17.04 :disappointed:

**Comment by andrekutianski** [comment] 2017-07-08 01:06
same here. Mint Linux 16

**Comment by Trondtr** [comment] 2017-07-10 16:25
We all have the problem (mac OS Sierra here), but no solution has been presented (?) :-(

**Comment by itsgratien** [comment] 2017-07-11 16:40
it doesn't work in ubuntu 16.04

**Comment by erikmcdaniel** [comment] 2017-08-18 07:15
+

**Comment by juanfernandoe** [comment] 2017-09-15 21:17
Same error on macos

**Comment by jasonrudolph** [comment] 2018-10-16 21:53
I've tried to reproduce this issue using the latest version of Atom (1.31.2) running on Ubuntu 18.04 and macOS High Sierra 10.13.6. I haven't been able to reproduce it.

Given that it's been more than a year since anyone has commented on this issue, it seems possible to me that this issue may have been resolved. (Maybe. 🤞) For that reason, I'm going to close this issue, but if you can still reproduce it, please open a new issue with the steps for reproducing the issue in the current version of Atom. :bow:

**Closed as completed by jasonrudolph** 2018-10-16 21:53 UTC
