### ISSUE TITLE
Failed to load the line-ending-selector package

### ISSUE THREAD

**Issue by fernandoPalaciosGit** [atom/line-ending-selector#6] opened 2015-08-31 17:00 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Microsoft Windows 10 Home
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.0.5
### Stack Trace

Failed to load the line-ending-selector package

```
At C:/Atom/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EBADF: bad file descriptor, write

Error: C:/Atom/resources/app.asar/node_modules/line-ending-selector/lib/status-bar-item.js: EBADF: bad file descriptor, write
  at Error (native)
  at Object.fs.writeSync (fs.js:657:20)
  at SyncWriteStream.write (fs.js:1906:6)
  at Function.log (C:\Atom\resources\app.asar\node_modules\babel-core\node_modules\debug\node.js:106:17)
  at enabled (C:\Atom\resources\app.asar\node_modules\babel-core\node_modules\debug\debug.js:117:11)
  at Logger.debug (C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\logger.js:92:31)
  at File.parse (C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:573:14)
  at File.parseCode (C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:691:20)
  at C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:167:12
  at File.wrap (C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\file\index.js:639:16)
  at Pipeline.transform (C:\Atom\resources\app.asar\node_modules\babel-core\lib\transformation\pipeline.js:165:17)
  at Object.exports.compile (C:\Atom\resources\app.asar\src\babel.js:51:16)
  at compileFileAtPath (C:\Atom\resources\app.asar\src\compile-cache.js:72:44)
  at Object.defineProperty.value [as .js] (C:\Atom\resources\app.asar\src\compile-cache.js:168:18)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Atom\resources\app.asar\node_modules\line-ending-selector\lib\main.js:20:22)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (C:\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Atom\resources\app.asar\src\package.js:759:34)
  at C:\Atom\resources\app.asar\src\package.js:190:28
  at Package.module.exports.Package.measure (C:\Atom\resources\app.asar\src\package.js:167:15)
  at Package.module.exports.Package.load (C:\Atom\resources\app.asar\src\package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Atom\resources\app.asar\src\package-manager.js:405:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Atom\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Atom\resources\app.asar\src\atom.js:667:21)
  at Object.<anonymous> (C:\Atom\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Atom\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.defineProperty.value [as .js] (C:\Atom\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Atom/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Atom/resources/app.asar/static/index.js:35:9)

```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by djengineerllc** [comment] 2015-11-06 17:50
I am getting the same issue everytime I open the Atom editor

**Comment by damieng** [comment] 2016-09-30 03:11
Haven't seen any additional reports of this error for 10 months, closing.

**Closed as completed by damieng** 2016-09-30 03:11 UTC

**Comment by myhubspot** [comment] 2017-04-19 16:15
@damieng You keep closing every report submitted when no solutions have been provided by the developer  and you say you havent seen any additional reports???? I have just installed Atom and my 1st impression of the software shows 2 issues, this of which is one of them .... dated:   20/04/17


[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package 0.6.2


### Stack Trace

Failed to activate the line-ending-selector package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module._compile (/app.asar/src/native-compile-cache.js:79:40)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /app.asar/node_modules/line-ending-selector/lib/main.js:20:22)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/app.asar/src/package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (/app.asar/src/package-manager.js:508:46)
    at /app.asar/src/atom-environment.js:826:28
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.3 
atom-material-ui 1.3.9 
nord-atom-ui 0.10.1 
Remote-FTP 0.10.5 
```

**Comment by damieng** [comment] 2017-04-19 16:24
@myhubspot The issue you are reporting is nothing like the bug that was closed here - the messages are "At .../line-ending-selector/lib/status-bar-item.js: EBADF: bad file descriptor, write" vs your issue of "An invalid or unexpected token in native-compile-cache"

Please open a new issue and use the template which will include running atom in safe mode - `atom --safe` that will help identify bugs or issues caused by third party packages.
