### ISSUE TITLE
Uncaught TypeError: _statusBarItem2.default is not a function

### ISSUE THREAD

**Issue by AvikSomanathan** [atom/line-ending-selector#20] opened 2016-01-02 15:14 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Pro
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.0
### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At C:\Users\Somanathan\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\line-ending-selector\lib\main.js:85

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (C:\Users\Somanathan\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\line-ending-selector\lib\main.js:85:23)
    at Provider.module.exports.Provider.provide (C:\Users\Somanathan\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Somanathan\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by damieng** [comment] 2016-09-30 03:15
Dupe of https://github.com/atom/line-ending-selector/issues/19

**Closed as completed by damieng** 2016-09-30 03:15 UTC
