### ISSUE TITLE
Uncaught TypeError: _statusBarItem2.default is not a function

### ISSUE THREAD

**Issue by aranchafoz** [atom/line-ending-selector#28] opened 2016-05-03 17:08 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Ubuntu 16.04
**Thrown From**: [line-ending-selector](https://github.com/atom/line-ending-selector) package, v0.3.1
### Stack Trace

Uncaught TypeError: _statusBarItem2.default is not a function

```
At /opt/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73

TypeError: _statusBarItem2.default is not a function
    at Object.consumeStatusBar (/opt/atom/resources/app.asar/node_modules/line-ending-selector/lib/main.js:73:23)
    at Provider.module.exports.Provider.provide (/opt/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /opt/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by pzfreo** [comment] 2016-06-06 07:22
I'm seeing the same with both 1.7.2 and the 1.8.0-beta4.

**Comment by damieng** [comment] 2016-09-30 03:14
dupe of https://github.com/atom/line-ending-selector/issues/19

**Closed as completed by damieng** 2016-09-30 03:14 UTC
