### ISSUE TITLE
Current line ending setting not respected

### ISSUE THREAD

**Issue by walterdeboer** [atom/line-ending-selector#52] opened 2018-01-02 14:44 UTC
When I open a linux file (line endings LF) in atom on Windows, the line endings selector shows the correct line-ending: LF

However when I add a line, the windows line-ending is used (CRLF), and the line-ending switches to Mixed. I would like the line-ending to stay at LF.

When I first explicitly set the line-ending to LF and then add a line, the expected line ending (LF) is used

**Comment by jasonrudolph** [comment] 2018-10-16 23:47
I've tried to reproduce this issue using the latest version of Atom (1.31.2), but I haven't been able to reproduce the behavior described above.

Given that it's been more than 9 months since this problem was reported, it seems possible to me that this issue may have been resolved. (Maybe. 🤞) For that reason, I'm going to close this issue, but if you can still reproduce it, please open a new issue with the steps for reproducing the problem in the current version of Atom. :bow:

**Closed as completed by jasonrudolph** 2018-10-16 23:47 UTC
