### ISSUE TITLE
Slow package load time and activation time.

### ISSUE THREAD

**Issue by doughsay** [atom/line-ending-selector#13] opened 2015-10-21 02:31 UTC
I recently decided to tweak my atom load times to see if I could squeeze some extra performance out of it.  I noticed that this package consistently takes a lot longer to load and activate than other packages.  Figured I'd mention it here...

<img width="719" alt="screen shot 2015-10-20 at 7 29 20 pm" src="https://cloud.githubusercontent.com/assets/221693/10626131/ebc279f0-7760-11e5-910a-739530ffebfb.png">

For now I just disabled this package, since I've never found myself needing it...

**Comment by whoisjake** [comment] 2015-10-27 16:32
I'm sitting near 65ms as well... slowest in my setup by a factor of 3

**Comment by burknator** [comment] 2015-10-28 21:44
Using 1.1.0-beta1 and it takes 43ms loading and another 44ms for activation. Seems a little strange to me too.

**Comment by adamtester** [comment] 2016-08-19 13:59
Quite bad on mine!
![screen shot 2016-08-19 at 2 58 52 pm](https://cloud.githubusercontent.com/assets/2249484/17812088/80163334-661d-11e6-85b1-238d72da7e84.png)

**Comment by jasonrudolph** [comment] 2018-10-16 21:47
I tried to reproduce this issue using the current version of Atom (1.31.2), but I'm unable to reproduce it. 

![screen shot 2018-10-16 at 17 45 29 pm](https://user-images.githubusercontent.com/2988/47049483-733ec700-d16b-11e8-9323-370694a5f5e1.png)

I'm going to close this issue, but if people are still observing this sub-par performance, please open a new issue to let us know. :bow:

**Closed as completed by jasonrudolph** 2018-10-16 21:47 UTC
Labels: help-wanted, performance
